name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build  -c Release -r linux-musl-x64  -p:ImportByWildcardBeforeSolution=false

      - id: download
        name: Download the release binary
        uses: actions/download-artifact@v3
      - name: Show files
        run: |
          pwd
          find
      - name: Copy files
        run: |
          mkdir out
          mv x86_64-apple-darwin/neocmakelsp out/neocmakelsp-x86_64-apple-darwin
          mv x86_64-pc-windows-msvc/neocmakelsp.exe out/neocmakelsp-x86_64-pc-windows-msvc.exe
          mv x86_64-unknown-linux-gnu/neocmakelsp out/neocmakelsp-x86_64-unknown-linux-gnu
          mv x86_64-unknown-linux-musl/neocmakelsp out/neocmakelsp-x86_64-unknown-linux-musl
          cd out
          sha256sum * > sha256sum
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
          draft: true
