name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-lates]

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -r linux-musl-x64

      - name: Check format and lints
        run: make check
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Test with the dotnet CLI
        run: dotnet test
